### PR TITLE
Add changelog

### LINKED ISSUE #95: We need a CHANGELOG
We were keeping a very high release pacing to get the infrastructure for filetype recognition off the ground. Now format_parser has stabilised and before other apps start taking us in as a dependency it might be useful to provide a changelog. For the formatting example see https://github.com/WeTransfer/zip_tricks/blob/master/CHANGELOG.md

### PR DESCRIPTION
**Pull request by bermannoah**
Will close #95.

### CODE REVIEW

**Comment by julik** [comment]
Uhm... no. If we add a Changelog it has to contain backdated stuff as well, otherwise it won't be very useful. See Patron and ZipTricks changelogs for inspiration :-)

**Comment by bermannoah** [comment]
@julik yep, it's backfilled at least as far as we have release numbers on github. (0.3.3 and 0.3.2 are the same as far as I can tell)

**Comment by julik** [comment]
Yeeees and wel also have commits mentioning "Bump version" which we can use for the releases that pre-date GH releases

**Comment by bermannoah** [comment]
Huzzah!

**Comment by julik** [comment]
Excellent!

**Pull request merged**
