### PR TITLE
Adopt Hippocratic License

### PR DESCRIPTION
**Pull request by bermannoah**
format_parser should not be used for evil, and we can update the license to reflect that. (I’d encourage adoption across other OSS projects in this org, but I feel like this is a good place to start.)

For more details: https://firstdonoharm.dev

(Was in #142) 

~Also asking what the license tag in the gemspec should be.~

### CODE REVIEW

**Comment by julik** [comment]
Pending reply from Coraline regarding the license tag we need to put in the gemspec.

**Comment by bermannoah** [comment]
@julik I’ve updated the license version and added info to the readme and gemspec. Should we do a major version bump here as well?

**Comment by julik** [comment]
Yes we should!

**Comment by bermannoah** [comment]
@julik 👍 1.0.0? 0.18.0?

**Comment by julik** [comment]
Oof... good question. I think here we are actually at liberty of going 0.18 since we were not at 1.0 to begin with. Let's make use of that fact!

**Comment by bermannoah** [comment]
Beautiful. Updated! :)

**Pull request merged**
